FORMAT: 1A
HOST: http://developer.oneboxtickets.com/venueconfig-api/index.html

# onebox-venueconfig-api

 API to get all the venue configurations from any external ticketing system.

 To do so, we have used a **API Blueprint** standard, **apiary** as an online editing and mocking tool, **aglio** to document it, **getsandbox** as a sandbox provider, **atom** as local editor and **mockapi** as a local sandbox.
 + [API Blueprint](https://apiblueprint.org/)
 + [apiary.io](http://docs.oneboxvenueconfigapi.apiary.io/)
 + [getsandbox.com](http://onebox-venueconfig-api.getsandbox.com/)
 + [aglio](https://github.com/danielgtaylor/aglio)
 + [atom](http://atom.io)
 + [mockapi](https://github.com/joliva-ob/mockapi)
 + [github](https://github.com/joliva-ob/onebox-venueconfig-api)
 + [onebox-developer](http://developer.oneboxtickets.com/venueconfig-api/)

## Venues Collection [/venueconfig-api/1.0/venues{?id,page}]
List all the venues with its key data and the activities allowed for each one. It is also allowed to filtering by Id and paging.
The following table contains the Spanish Soccer compatibility response fields descriptions:

| Response Field                   | Description                             |
|----------------------------------|-----------------------------------------|
| venue                            | Spanish: recinto club                   |
| capacity                         | Spanish: aforo                          |
| activities                       | Spanish: competición                    |

### List All Venues [GET]

+ Request

  + Headers

            Authorization: Bearer OAUTH2_TOKEN
            Accept: application/json

+ Parameters
    + id (optional, text) ... Filter by a given venue id.
    + page (optional, number) ... Paginate response to the given page number

+ Response 200 (application/json)

        {
          "collection":
          {
            "version": "1.0",
            "href": "http://www.oneboxtm.com/venueconfig-api/1.0/venues",
            "trace_id": "94abc26e-173a-4ab2-a71b-863aed20f656",
            "span_id": "34abc26e-173a-4ab2-a71b-863aed20f622",
            "request_date": "2015-08-05T08:40:51.620Z",
            "http_status_code": 200,
            "error_code": "",
            "error_description": "",
            "parameters":
            {
              "id": "",
              "page": 2
            },
            "venues": [
              {
                "id": "51",
                "name": "Futbol Club Barcelona",
                "ip": "10.234.22.5",
                "port": 60000,
                "capacities": [
                  {
                    "id": "1",
                    "name": "LIGA",
                    "activities": [
                      {
                        "id": "1",
                        "name": "LIGA"
                      },
                      {
                        "id": "2",
                        "name": "SUPERCOPA"
                      },
                      {
                        "id": "3",
                        "name": "CHAMPIONS"
                      },
                      {
                        "id": "4",
                        "name": "COPA DEL REY"
                      }
                    ]
                  },
                  {
                    "id": "2",
                    "name": "PARKING",
                    "activities": [
                      {
                        "id": "1",
                        "name": "PARKING"
                      }
                    ]
                  },
                  {
                    "id": "3",
                    "name": "EUROPA",
                    "activities": [
                      {
                        "id": "1",
                        "name": "UEFA"
                      },
                      {
                        "id": "2",
                        "name": "CHAMPIONS"
                      }
                    ]
                  },
                  {
                    "id": "4",
                    "name": "CONCIERTOS",
                    "activities": [
                      {
                        "id": "1",
                        "name": "UNICA"
                      }
                    ]
                  }
                ],
                "settings":
                {
                  "confirmation_release_time": 5,
                  "cancellation_release_time": 60,
                  "pre_order_trials_limit": 3,
                  "second_market": false,
                  "partners_selling": true,
                  "max_tickets_order": 5,
                  "allowed_seat_status": [
                    {
                      "id": "L"
                    },
                    {
                      "id": "S"
                    },
                    {
                      "id": "X"
                    }
                  ],
                  "pending_booking_seat_status": "Z",
                  "pending_booking_confirmation_allowed": false
                },
                "links" : [
                  {
                    "rel" : "events",
                    "href" : "http://www.oneboxtm.com/venueconfig-api/1.0/venues/51/events/",
                    "prompt" : "Events"
                  }
                ]
              },
              {
                "id": "37",
                "name": "Club Atlético de Madrid",
                "ip": "10.234.22.1",
                "port": 60000,
                "capacities": [
                  {
                    "id": "1",
                    "name": "LIGA",
                    "activities": [
                      {
                        "id": "1",
                        "name": "LIGA"
                      },
                      {
                        "id": "2",
                        "name": "SUPERCOPA"
                      },
                      {
                        "id": "3",
                        "name": "CHAMPIONS"
                      },
                      {
                        "id": "4",
                        "name": "COPA DEL REY"
                      }
                    ]
                  },
                  {
                    "id": "2",
                    "name": "PARKING",
                    "activities": [
                      {
                        "id": "1",
                        "name": "PARKING"
                      }
                    ]
                  },
                  {
                    "id": "3",
                    "name": "EUROPA",
                    "activities": [
                      {
                        "id": "1",
                        "name": "UEFA"
                      },
                      {
                        "id": "2",
                        "name": "CHAMPIONS"
                      }
                    ]
                  },
                  {
                    "id": "4",
                    "name": "CONCIERTOS",
                    "activities": [
                      {
                        "id": "1",
                        "name": "UNICA"
                      }
                    ]
                  }
                ],
                "settings":
                {
                  "confirmation_release_time": 5,
                  "cancellation_release_time": 60,
                  "pre_order_trials_limit": 3,
                  "second_market": false,
                  "partner_selling": true,
                  "max_tickets_order": 5,
                  "allowed_seat_status": [
                    {
                      "id": "L"
                    },
                    {
                      "id": "S"
                    },
                    {
                      "id": "X"
                    }
                  ],
                  "pending_booking_seat_status": "Z",
                  "pending_booking_confirmation_allowed": false
                },
                "links" : [
                  {
                    "rel" : "events",
                    "href" : "http://www.oneboxtm.com/venueconfig-api/1.0/venues/37/events/",
                    "prompt" : "Events"
                  }
                ]
              }
            ],
            "links": [
              {
                "name": "next_page",
                "prompt": "Next",
                "rel": "next",
                "href": "http://www.oneboxtm.com/venueconfig-api/1.0/venues/page/3",
                "render": "link"
              },
              {
                "name": "previous_page",
                "prompt": "Bext",
                "rel": "back",
                "href": "http://www.oneboxtm.com/venueconfig-api/1.0/venues/page/1",
                "render": "link"
              }
            ]

          }
        }

+ Response 204 (application/json)

+ Response 400 (application/json)

        {
          "collection":
          {
            "version": "1.0",
            "href": "http://www.oneboxtm.com/venueconfig-api/1.0/venues",
            "trace_id": "94abc26e-173a-4ab2-a71b-863aed20f656",
            "span_id": "34abc26e-173a-4ab2-a71b-863aed20f622",
            "request_date": "2015-08-05T08:40:51.620Z",
            "http_status_code": 400,
            "error_code": "Bad Request",
            "error_description": "There was a syntax error, check your params request and try it again."
            "parameters":
            {
              "id": "",
              "page": 1
            },
            "venues": [],
            "links": []
          }
        }

+ Response 401 (application/json)

        {
          "collection":
          {
            "version": "1.0",
            "href": "http://www.oneboxtm.com/venueconfig-api/1.0/venues",
            "trace_id": "94abc26e-173a-4ab2-a71b-863aed20f656",
            "span_id": "34abc26e-173a-4ab2-a71b-863aed20f622",
            "request_date": "2015-08-05T08:40:51.620Z",
            "http_status_code": 401,
            "error_code": "Unauthorized",
            "error_description": "Full authentication is required to access this resource"
            "parameters":
            {
              "id": "",
              "page": 1
            },
            "venues": [],
            "links": []
          }
        }

## Venue date events Collection [/venueconfig-api/1.0/venues/{venue_id}/events{?id,page}]
List all the events from a given venue with its key data. It is also allowed to filtering by Id and paging.
The following table contains the Spanish Soccer compatibility response fields descriptions:

| Response Field                   | Description                             |
|----------------------------------|-----------------------------------------|
| supporter                        | Spanish: simpatizante                   |
| subscriber                       | Spanish: abonado                        |
| partner                          | Spanish: socio                          |
| suporter_companion               | Spanish: acompañantes simpatizantes     |

### List All Venue Events [GET]

+ Request

  + Headers

            Authorization: Bearer OAUTH2_TOKEN
            Accept: application/json

+ Parameters
    + venue_id (required, text) ... Identifies a specific venue.
    + id (optional, text) ... Filter by a given event.
    + page (optional, number) ... Paginate response to the given page number.

+ Response 200 (application/json)

        {
          "collection":
          {
            "version": "1.0",
            "href": "http://www.oneboxtm.com/venueconfig-api/1.0/venues/51/events",
            "trace_id": "94abc26e-173a-4ab2-a71b-863aed20f656",
            "span_id": "34abc26e-173a-4ab2-a71b-863aed20f622",
            "request_date": "2015-08-05T08:40:51.620Z",
            "http_status_code": 200,
            "error_code": "",
            "error_description": "",
            "parameters":
            {
              "venue_id": "51",
              "id": "",
              "page": 2
            },
            "events": [
              {
                "id": "125",
                "name": "Partido de prueba",
                "capacity_id": 1,
                "activity_id": 1,
                "round": "10",
                "date": "2015-10-30T17:00:00+01:00",
                "final_date": true,
                "season": "14-15",
                "zone_selling": true,
                "second_market": true,
                "package_selling": false,
                "partner_selling": true,
                "fun_selling": false,
                "released_seats_selling": true,
                "early_released_seats_selling": true,
                "available": true,
                "general_admission_start_date": "2015-10-30T17:00:00+01:00",
                "general_admission_end_date": "2015-10-30T17:00:00+01:00",
                "general_admission_no_print_start_date": "2015-10-30T17:00:00+01:00",
                "general_admission_no_print_end_date": "2015-10-30T17:00:00+01:00",
                "supporter_start_date": "2015-10-30T17:00:00+01:00",
                "supporter_end_date": "2015-10-30T17:00:00+01:00",
                "supporter_no_print_start_date": "2015-10-30T17:00:00+01:00",
                "supporter_no_print_end_date": "2015-10-30T17:00:00+01:00",
                "subscriber_start_date": "2015-10-30T17:00:00+01:00",
                "subscriber_end_date": "2015-10-30T17:00:00+01:00",
                "subscriber_no_print_start_date": "2015-10-30T17:00:00+01:00",
                "subscriber_no_print_end_date": "2015-10-30T17:00:00+01:00",
                "partner_start_date": "2015-10-30T17:00:00+01:00",
                "partner_end_date": "2015-10-30T17:00:00+01:00",
                "partner_no_print_start_date": "2015-10-30T17:00:00+01:00",
                "partner_no_print_end_date": "2015-10-30T17:00:00+01:00",
                "general_admission_tickets_limit": 1,
                "preferred_tickets_limit": 1,
                "supporter_companion_tickets_limit": 2,
                "supporter_tickets_limit:" 3,
                "parent_zones": [
                  {
                    "id": "1",
                    "name": "GRADA PREFERENCIAL",
                    "update_date": "2015-10-30T17:00:00+01:00",
                    "zones": [
                        {
                          "id": "126",
                          "name": "GRADA PREFERENCIA BAJA",
                          "gates": 54
                        },
                        {
                          "id": "127",
                          "name": "GRADA PREFERENCIA ALTA",
                          "gates": 1
                        }
                      ],
                      "prices": [
                        {
                          "id": "50",
                          "name": "Grada PREF BAJA",
                          "price": 60,00
                        }
                      ]
                  },
                  {
                    "id": "2",
                    "name": "GRADA VIP",
                    "update_date": "2015-10-30T17:00:00+01:00",
                    "zones": [
                        {
                          "id": "12",
                          "name": "GRADA VIP BAJA",
                          "gates": 54
                        },
                        {
                          "id": "13",
                          "name": "GRADA VIP ALTA",
                          "gates": 1
                        }
                      ],
                      "prices": [
                        {
                          "id": "50",
                          "name": "Grada PREF BAJA",
                          "price": 60,00
                        }
                      ]
                  }
                ],
                "links" : [
                  {
                    "rel" : "capacities",
                    "href" : "http://www.oneboxtm.com/venueconfig-api/1.0/venues/51/events/125/capacities",
                    "prompt" : "Capacities"
                  }
                ]
              }
          ],

          "links": [
            {
              "name": "next_page",
              "prompt": "Next",
              "rel": "next",
              "href": "http://www.oneboxtm.com/venueconfig-api/1.0/venues/125/events/?page=3",
              "render": "link"
            },
            {
              "name": "previous_page",
              "prompt": "Bext",
              "rel": "back",
              "href": "http://www.oneboxtm.com/venueconfig-api/1.0/venues/125/events/?page=1",
              "render": "link"
            }
          ]
         }
        }

+ Response 204 (application/json)

+ Response 400 (application/json)

        {
          "collection":
          {
            "version": "1.0",
            "href": "http://www.oneboxtm.com/venueconfig-api/1.0/venues/125/events",
            "trace_id": "94abc26e-173a-4ab2-a71b-863aed20f656",
            "span_id": "34abc26e-173a-4ab2-a71b-863aed20f622",
            "request_date": "2015-08-05T08:40:51.620Z",
            "http_status_code": 400,
            "error_code": "Bad Request",
            "error_description": "There was a syntax error, check your params request and try it again."
            "parameters":
            {
              "venue_id": "",
              "id": "",
              "page":
            },
            "venues": [],
            "links": []
          }
        }

+ Response 401 (application/json)

        {
          "collection":
          {
            "version": "1.0",
            "href": "http://www.oneboxtm.com/venueconfig-api/1.0/venues/125/events",
            "trace_id": "94abc26e-173a-4ab2-a71b-863aed20f656",
            "span_id": "34abc26e-173a-4ab2-a71b-863aed20f622",
            "request_date": "2015-08-05T08:40:51.620Z",
            "http_status_code": 401,
            "error_code": "Unauthorized",
            "error_description": "Full authentication is required to access this resource"
            "parameters":
            {
              "venue_id": "",
              "id": "",
              "page": 1
            },
            "venues": [],
            "links": []
          }
        }

## Venue seating capacity details Collection [/venueconfig-api/1.0/venues/{venue_id}/capacities{?id,page}]
List all the seating capacities from a given venue with its key data. It is also allowed to filtering by Id and paging.
The following table contains the Spanish Soccer compatibility response fields descriptions:

| Response Field                   | Description                             |
|----------------------------------|-----------------------------------------|
| entrance                         | Spanish: boca                           |
| gate                             | Spanish: puerta                         |
| block                            | Spanish: escalera                       |
| sector                           | Spanish: vomitorio                      |

### List All Seating Capacities of a given Venue/Event [GET]

+ Request

  + Headers

            Authorization: Bearer OAUTH2_TOKEN
            Accept: application/json

+ Parameters
    + venue_id (required, text) ... Identifies a specific venue.
    + id (optional, text) ... Filter by a given seating capacity.
    + page (optional, number) ... Paginate response to the given page number.

+ Response 200 (application/json)

        {
          "collection":
          {
            "version": "1.0",
            "href": "http://www.oneboxtm.com/venueconfig-api/1.0/venues/125/capacities",
            "trace_id": "94abc26e-173a-4ab2-a71b-863aed20f656",
            "span_id": "34abc26e-173a-4ab2-a71b-863aed20f622",
            "request_date": "2015-08-05T08:40:51.620Z",
            "http_status_code": 200,
            "error_code": "",
            "error_description": "",
            "parameters":
            {
              "venue_id": "125",
              "id": "1",
              "page": 2
            },
            "capacities": [
              {
                "id": "1",
                "name": "LIGA",
                "creation_date": "",
                "update_date": "2014-07-30T14:39:33.48+02:00",
                "zones": [
                  {
                    "id": "1",
                    "name": "GRADA PREFERENCIAL",
                    "gates": 54,
                    "seats": [
                        {
                          "id": "126",
                          "row": 20,
                          "seat": 3,
                          "entrance": "",
                          "gate": "1",
                          "block": "1",
                          "sector": ""
                        },
                        {
                          "id": "127",
                          "row": 20,
                          "seat": 4,
                          "entrance": "",
                          "gate": "1",
                          "block": "1",
                          "sector": ""
                        }
                    ]
                  },
                  {
                    "id": "2",
                    "name": "GRADA VIP",
                    "creation_date": "",
                    "update_date": "2014-07-30T14:39:33.48+02:00",
                    "gates": 2,
                    "seats": [
                        {
                          "id": "128",
                          "row": 10,
                          "seat": 1,
                          "entrance": "A",
                          "gate": "1",
                          "block": "1",
                          "sector": ""
                        },
                        {
                          "id": "129",
                          "row": 10,
                          "seat": 9,
                          "entrance": "A",
                          "gate": "1",
                          "block": "1",
                          "sector": ""
                        }
                    ]
                  }
                ]
              }
          ],
          "links": [
            {
              "name": "next_page",
              "prompt": "Next",
              "rel": "next",
              "href": "http://www.oneboxtm.com/venueconfig-api/1.0/venues/125/capacities?page=3",
              "render": "link"
            },
            {
              "name": "previous_page",
              "prompt": "Bext",
              "rel": "back",
              "href": "http://www.oneboxtm.com/venueconfig-api/1.0/venues/125/capacities?page=1",
              "render": "link"
            }
          ]
         }
        }

+ Response 204 (application/json)

+ Response 400 (application/json)

        {
          "collection":
          {
            "version": "1.0",
            "href": "http://www.oneboxtm.com/venueconfig-api/1.0/venues/125/capacities",
            "trace_id": "94abc26e-173a-4ab2-a71b-863aed20f656",
            "span_id": "34abc26e-173a-4ab2-a71b-863aed20f622",
            "request_date": "2015-08-05T08:40:51.620Z",
            "http_status_code": 400,
            "error_code": "Bad Request",
            "error_description": "There was a syntax error, check your params request and try it again."
            "parameters":
            {
              "venue_id": "",
              "id": "",
              "page":
            },
            "venues": [],
            "links": []
          }
        }

+ Response 401 (application/json)

        {
          "collection":
          {
            "version": "1.0",
            "href": "http://www.oneboxtm.com/venueconfig-api/1.0/capacities",
            "trace_id": "94abc26e-173a-4ab2-a71b-863aed20f656",
            "span_id": "34abc26e-173a-4ab2-a71b-863aed20f622",
            "request_date": "2015-08-05T08:40:51.620Z",
            "http_status_code": 401,
            "error_code": "Unauthorized",
            "error_description": "Full authentication is required to access this resource"
            "parameters":
            {
              "venue_id": "",
              "id": "",
              "page": 1
            },
            "venues": [],
            "links": []
          }
        }
