FORMAT: 1A

HOST: http://onebox-api-url/1.0/venueconfig-api

# onebox-venueconfig-api

 API to get all the venue configurations from any external ticketing system.

 To do so, we have used a **API Blueprint** standard, **apiary** as an online editing and mocking tool, **aglio** to document it, **getsandbox** as a sandbox provider, **atom** as local editor and **mockapi** as a local sandbox.
 + [API Blueprint](https://apiblueprint.org/)
 + [apiary.io](http://docs.oneboxvenueconfigapi.apiary.io/)
 + [getsandbox.com](http://onebox-venueconfig-api.getsandbox.com/)
 + [aglio](https://github.com/danielgtaylor/aglio)
 + [atom](http://atom.io)
 + [mockapi](https://github.com/joliva-ob/mockapi)
 + [github](https://github.com/joliva-ob/onebox-venueconfig-api)
 + [onebox-developer](http://developer.oneboxtickets.com/venueconfig-api/)

## Venues Collection [/venueconfig-api/1.0/venues{?id,page}]

List all the venues with its key data and the activities allowed for each one. It is also allowed to filtering by Id and paging.
The following table contains the Spanish Soccer compatibility response fields descriptions:

| Response Field                   | Description                             |
|----------------------------------|-----------------------------------------|
| venue                            | Spanish: recinto club                   |
| capacity                         | Spanish: aforo                          |
| activities                       | Spanish: competición                    |

+ Parameters

    + id (optional, text) ... Filter by a given venue id.
    + page (optional, number) ... Paginate response to the given page number



### List All Venues [GET]

+ Request

    + Headers

            Authorization: Bearer OAUTH2_TOKEN
            Accept: application/json

+ Response 200 (application/json)

        {
          "collection":
          {
            "version": "1.0",
            "href": "http://www.oneboxtm.com/venueconfig-api/1.0/venues",
            "trace_id": "94abc26e-173a-4ab2-a71b-863aed20f656",
            "span_id": "34abc26e-173a-4ab2-a71b-863aed20f622",
            "request_date": "2015-08-05T08:40:51.620Z",
            "http_status_code": 200,
            "error_code": "",
            "error_description": "",
            "parameters":
            {
              "page": 2
            },
            "venues": [
              {
                "id": "51",
                "name": "Futbol Club Barcelona",
                "version": 1234567890,
                "ip": "10.234.22.5",
                "port": 60000,
                "capacities": [
                  {
                    "id": "1",
                    "name": "LIGA",
                    "activities": [
                      {
                        "id": "1",
                        "name": "LIGA"
                      },
                      {
                        "id": "2",
                        "name": "SUPERCOPA"
                      },
                      {
                        "id": "3",
                        "name": "CHAMPIONS"
                      },
                      {
                        "id": "4",
                        "name": "COPA DEL REY"
                      }
                    ],
                    "links" : [ {
                      "rel" : "events",
                      "href" : "http://www.oneboxtm.com/venueconfig-api/1.0/venues/51/capacities/1/events",
                      "prompt" : "Events"
                    }, {
                      "rel" : "capacity",
                      "href" : "http://www.oneboxtm.com/venueconfig-api/1.0/venues/51/capacities/1",
                      "prompt" : "Capacity"
                    } ]
                  },
                  {
                    "id": "2",
                    "name": "PARKING",
                    "activities": [
                      {
                        "id": "1",
                        "name": "PARKING"
                      }
                    ],
                    "links" : [ {
                      "rel" : "events",
                      "href" : "http://www.oneboxtm.com/venueconfig-api/1.0/venues/51/capacities/2/events",
                      "prompt" : "Events"
                    }, {
                      "rel" : "capacity",
                      "href" : "http://www.oneboxtm.com/venueconfig-api/1.0/venues/51/capacities/2",
                      "prompt" : "Capacity"
                    } ]
                  },
                  {
                    "id": "3",
                    "name": "EUROPA",
                    "activities": [
                      {
                        "id": "1",
                        "name": "UEFA"
                      },
                      {
                        "id": "2",
                        "name": "CHAMPIONS"
                      }
                    ],
                    "links" : [ {
                      "rel" : "events",
                      "href" : "http://www.oneboxtm.com/venueconfig-api/1.0/venues/51/capacities/3/events",
                      "prompt" : "Events"
                    }, {
                      "rel" : "capacity",
                      "href" : "http://www.oneboxtm.com/venueconfig-api/1.0/venues/51/capacities/3",
                      "prompt" : "Capacity"
                    } ]
                  },
                  {
                    "id": "4",
                    "name": "CONCIERTOS",
                    "activities": [
                      {
                        "id": "1",
                        "name": "UNICA"
                      }
                    ],
                    "links" : [ {
                      "rel" : "events",
                      "href" : "http://www.oneboxtm.com/venueconfig-api/1.0/venues/51/capacities/4/events",
                      "prompt" : "Events"
                    }, {
                      "rel" : "capacity",
                      "href" : "http://www.oneboxtm.com/venueconfig-api/1.0/venues/51/capacities/4",
                      "prompt" : "Capacity"
                    } ]
                  }
                ],
                "settings":
                {
                  "confirmation_release_time": 5,
                  "cancellation_release_time": 60,
                  "pre_order_trials_limit": 3,
                  "second_market": false,
                  "partners_selling": true,
                  "max_tickets_order": 5,
                  "allowed_seat_status": [
                    {
                      "id": "L"
                    },
                    {
                      "id": "S"
                    },
                    {
                      "id": "X"
                    }
                  ],
                  "pending_booking_seat_status": "Z",
                  "pending_booking_confirmation_allowed": false
                },
                "links" : [
                  {
                    "rel" : "capacities",
                    "href" : "http://www.oneboxtm.com/venueconfig-api/1.0/venues/51/capacities",
                    "prompt" : "Capacities"
                  }
                ]
              },
              {
                "id": "37",
                "name": "Club Atlético de Madrid",
                "version": 1234567891,
                "ip": "10.234.22.1",
                "port": 60000,
                "capacities": [
                  {
                    "id": "1",
                    "name": "LIGA",
                    "activities": [
                      {
                        "id": "1",
                        "name": "LIGA"
                      },
                      {
                        "id": "2",
                        "name": "SUPERCOPA"
                      },
                      {
                        "id": "3",
                        "name": "CHAMPIONS"
                      },
                      {
                        "id": "4",
                        "name": "COPA DEL REY"
                      }
                    ],
                    "links" : [ {
                      "rel" : "events",
                      "href" : "http://www.oneboxtm.com/venueconfig-api/1.0/venues/37/capacities/1/events",
                      "prompt" : "Events"
                    }, {
                      "rel" : "capacity",
                      "href" : "http://www.oneboxtm.com/venueconfig-api/1.0/venues/37/capacities/1",
                      "prompt" : "Capacity"
                    } ]
                  },
                  {
                    "id": "2",
                    "name": "PARKING",
                    "activities": [
                      {
                        "id": "1",
                        "name": "PARKING"
                      }
                    ],
                    "links" : [ {
                      "rel" : "events",
                      "href" : "http://www.oneboxtm.com/venueconfig-api/1.0/venues/51/capacities/2/events",
                      "prompt" : "Events"
                    }, {
                      "rel" : "capacity",
                      "href" : "http://www.oneboxtm.com/venueconfig-api/1.0/venues/51/capacities/2",
                      "prompt" : "Capacity"
                    } ]
                  },
                  {
                    "id": "3",
                    "name": "EUROPA",
                    "activities": [
                      {
                        "id": "1",
                        "name": "UEFA"
                      },
                      {
                        "id": "2",
                        "name": "CHAMPIONS"
                      }
                    ],
                    "links" : [ {
                      "rel" : "events",
                      "href" : "http://www.oneboxtm.com/venueconfig-api/1.0/venues/37/capacities/3/events",
                      "prompt" : "Events"
                    }, {
                      "rel" : "capacity",
                      "href" : "http://www.oneboxtm.com/venueconfig-api/1.0/venues/37/capacities/3",
                      "prompt" : "Capacity"
                    } ]
                  },
                  {
                    "id": "4",
                    "name": "CONCIERTOS",
                    "activities": [
                      {
                        "id": "1",
                        "name": "UNICA"
                      }
                    ],
                    "links" : [ {
                      "rel" : "events",
                      "href" : "http://www.oneboxtm.com/venueconfig-api/1.0/venues/51/capacities/4/events",
                      "prompt" : "Events"
                    }, {
                      "rel" : "capacity",
                      "href" : "http://www.oneboxtm.com/venueconfig-api/1.0/venues/51/capacities/4",
                      "prompt" : "Capacity"
                    } ]
                  }
                ],
                "settings":
                {
                  "confirmation_release_time": 5,
                  "cancellation_release_time": 60,
                  "pre_order_trials_limit": 3,
                  "second_market": false,
                  "partner_selling": true,
                  "max_tickets_order": 5,
                  "allowed_seat_status": [
                    {
                      "id": "L"
                    },
                    {
                      "id": "S"
                    },
                    {
                      "id": "X"
                    }
                  ],
                  "pending_booking_seat_status": "Z",
                  "pending_booking_confirmation_allowed": false
                },
                "links" : [
                  {
                    "rel" : "capacities",
                    "href" : "http://onebox-int-avet-venueconfig-connectorfctest/venueconfig-api/1.0/venues/37/capacities",
                    "prompt" : "Capacities"
                  }
                ]
              }
            ],
            "links": [
              {
                "name": "next_page",
                "prompt": "Next",
                "rel": "next",
                "href": "http://www.oneboxtm.com/venueconfig-api/1.0/venues/page/3",
                "render": "link"
              },
              {
                "name": "previous_page",
                "prompt": "Bext",
                "rel": "back",
                "href": "http://www.oneboxtm.com/venueconfig-api/1.0/venues/page/1",
                "render": "link"
              }
            ]

          }
        }

+ Response 400 (application/json)

        {
          "collection":
          {
            "version": "1.0",
            "href": "http://www.oneboxtm.com/venueconfig-api/1.0/venues",
            "trace_id": "94abc26e-173a-4ab2-a71b-863aed20f656",
            "span_id": "34abc26e-173a-4ab2-a71b-863aed20f622",
            "request_date": "2015-08-05T08:40:51.620Z",
            "http_status_code": 400,
            "error_code": "Bad Request",
            "error_description": "There was a syntax error, check your params request and try it again."
            "parameters":
            {
              "id": "",
              "page": 1
            }
            "links": []
          }
        }

+ Response 401 (application/json)

        {
          "collection":
          {
            "version": "1.0",
            "href": "http://www.oneboxtm.com/venueconfig-api/1.0/venues",
            "trace_id": "94abc26e-173a-4ab2-a71b-863aed20f656",
            "span_id": "34abc26e-173a-4ab2-a71b-863aed20f622",
            "request_date": "2015-08-05T08:40:51.620Z",
            "http_status_code": 401,
            "error_code": "Unauthorized",
            "error_description": "Full authentication is required to access this resource"
            "parameters":
            {
              "id": "",
              "page": 1
            }
            "links": []
          }
        }

## Venue Resource Operations [/venueconfig-api/1.0/venues/{id}{?version,latest_from}]

Retrieve a concrete resource representation of a venue specified by its *id*. For a concrete venue a specific version of the venue can be retrieved using the parameter `version`. If you do not know the version you have 2 possibilities:
 * Getting the latest version by not specifying `version` nor `latest_from`.
 * Specify the last valid version that you know as `latest_from` value. This will cause to get the latest version of the venue if there is one. In case that there is no newer version a `404` is returned.

+ Parameters

    + id (text) ... The venue identifier
    + version (optional, number) ... Return a specific version of the venue. Mutualy exclusive with `latest_from`
    + latest_from (optional, number) ... Given a version it returns the most recent venue's version grather than the provided version. Mutualy exclusive with `version`

### Retieve a single venue resource [GET]

+ Request  /venueconfig-api/1.0/venues/51

    + Headers

            Authorization: Bearer OAUTH2_TOKEN
            Accept: application/json

+ Response 200 (application/json)

        {
            "collection":
            {
              "version": "1.0",
              "href": "http://www.oneboxtm.com/venueconfig-api/1.0/venues",
              "trace_id": "94abc26e-173a-4ab2-a71b-863aed20f656",
              "span_id": "34abc26e-173a-4ab2-a71b-863aed20f622",
              "request_date": "2015-08-05T08:40:51.620Z",
              "http_status_code": 200,
              "error_code": "",
              "error_description": "",
              "parameters":
              {
                "id": "51"
              },
              "venues": [
                {
                  "id": "51",
                  "name": "Futbol Club Barcelona",
                  "version": 1234567890,
                  "ip": "10.234.22.5",
                  "port": 60000,
                  "capacities": [
                    {
                      "id": "1",
                      "name": "LIGA",
                      "activities": [
                        {
                          "id": "1",
                          "name": "LIGA"
                        },
                        {
                          "id": "2",
                          "name": "SUPERCOPA"
                        },
                        {
                          "id": "3",
                          "name": "CHAMPIONS"
                        },
                        {
                          "id": "4",
                          "name": "COPA DEL REY"
                        }
                      ],
                      "links" : [ {
                        "rel" : "events",
                        "href" : "http://www.oneboxtm.com/venueconfig-api/1.0/venues/51/capacities/1/events",
                        "prompt" : "Events"
                      }, {
                        "rel" : "capacity",
                        "href" : "http://www.oneboxtm.com/venueconfig-api/1.0/venues/51/capacities/1",
                        "prompt" : "Capacity"
                      } ]
                    },
                    {
                      "id": "2",
                      "name": "PARKING",
                      "activities": [
                        {
                          "id": "1",
                          "name": "PARKING"
                        }
                      ],
                      "links" : [ {
                        "rel" : "events",
                        "href" : "http://www.oneboxtm.com/venueconfig-api/1.0/venues/51/capacities/2/events",
                        "prompt" : "Events"
                      }, {
                        "rel" : "capacity",
                        "href" : "http://www.oneboxtm.com/venueconfig-api/1.0/venues/51/capacities/2",
                        "prompt" : "Capacity"
                      } ]
                    },
                    {
                      "id": "3",
                      "name": "EUROPA",
                      "activities": [
                        {
                          "id": "1",
                          "name": "UEFA"
                        },
                        {
                          "id": "2",
                          "name": "CHAMPIONS"
                        }
                      ],
                      "links" : [ {
                        "rel" : "events",
                        "href" : "http://www.oneboxtm.com/venueconfig-api/1.0/venues/51/capacities/3/events",
                        "prompt" : "Events"
                      }, {
                        "rel" : "capacity",
                        "href" : "http://www.oneboxtm.com/venueconfig-api/1.0/venues/51/capacities/3",
                        "prompt" : "Capacity"
                      } ]
                    },
                    {
                      "id": "4",
                      "name": "CONCIERTOS",
                      "activities": [
                        {
                          "id": "1",
                          "name": "UNICA"
                        }
                      ],
                      "links" : [ {
                        "rel" : "events",
                        "href" : "http://www.oneboxtm.com/venueconfig-api/1.0/venues/51/capacities/4/events",
                        "prompt" : "Events"
                      }, {
                        "rel" : "capacity",
                        "href" : "http://www.oneboxtm.com/venueconfig-api/1.0/venues/51/capacities/4",
                        "prompt" : "Capacity"
                      } ]
                    }
                  ],
                  "settings":
                  {
                    "confirmation_release_time": 5,
                    "cancellation_release_time": 60,
                    "pre_order_trials_limit": 3,
                    "second_market": false,
                    "partners_selling": true,
                    "max_tickets_order": 5,
                    "allowed_seat_status": [
                      {
                        "id": "L"
                      },
                      {
                        "id": "S"
                      },
                      {
                        "id": "X"
                      }
                    ],
                    "pending_booking_seat_status": "Z",
                    "pending_booking_confirmation_allowed": false
                  },
                  "links" : [
                    {
                      "rel" : "capacities",
                      "href" : "http://www.oneboxtm.com/venueconfig-api/1.0/venues/51/capacities",
                      "prompt" : "Capacities"
                    }
                  ]
                }
              ],
              "links": []

            }
        }

+ Response 204 (application/json)

+ Request /venueconfig-api/1.0/venues/astringid

    + Headers

            Authorization: Bearer OAUTH2_TOKEN
            Accept: application/json

+ Response 400 (application/json)

        {
            "collection":
            {
                "version": "1.0",
                "href": "http://www.oneboxtm.com/venueconfig-api/1.0/venues",
                "trace_id": "94abc26e-173a-4ab2-a71b-863aed20f656",
                "span_id": "34abc26e-173a-4ab2-a71b-863aed20f622",
                "request_date": "2015-08-05T08:40:51.620Z",
                "http_status_code": 400,
                "error_code": "Bad Request",
                "error_description": "There was a syntax error, check your params request and try it again."
                "parameters":
                {
                    "id": "astringid"
                }
                "links": []
            }
        }

+ Request /venueconfig-api/1.0/venues/1?version=12&latest_from=45

    + Headers

            Authorization: Bearer OAUTH2_TOKEN
            Accept: application/json

+ Response 400 (application/json)

        {
            "collection":
            {
                "version": "1.0",
                "href": "http://www.oneboxtm.com/venueconfig-api/1.0/venues",
                "trace_id": "94abc26e-173a-4ab2-a71b-863aed20f656",
                "span_id": "34abc26e-173a-4ab2-a71b-863aed20f622",
                "request_date": "2015-08-05T08:40:51.620Z",
                "http_status_code": 400,
                "error_code": "Bad Request",
                "error_description": "version and lastFrom can not be specified at the same time, only one of them can be specified"
                "parameters":
                {
                    "id": "1",
                    "version": 12,
                    "latest_from": 45
                }
                "links": []
            }
        }

+ Request /venueconfig-api/1.0/venues/1

    + Headers

            Accept: application/json

+ Response 401 (application/json)

        {
          "collection":
          {
            "version": "1.0",
            "href": "http://www.oneboxtm.com/venueconfig-api/1.0/venues",
            "trace_id": "94abc26e-173a-4ab2-a71b-863aed20f656",
            "span_id": "34abc26e-173a-4ab2-a71b-863aed20f622",
            "request_date": "2015-08-05T08:40:51.620Z",
            "http_status_code": 401,
            "error_code": "Unauthorized",
            "error_description": "Full authentication is required to access this resource"
            "parameters":
            {
              "id": "2"
            }
            "links": []
          }
        }

## Venue's capacity's events Collection [/venueconfig-api/1.0/venues/{venue_id}/capacities/{capacity_id}/events{?id,page}]

List all the events from a given venue's capacity with its key data. It is also allowed to filtering by Id and paging.
The following table contains the Spanish Soccer compatibility response fields descriptions:

| Response Field                   | Description                             |
|----------------------------------|-----------------------------------------|
| supporter                        | Spanish: simpatizante                   |
| subscriber                       | Spanish: abonado                        |
| partner                          | Spanish: socio                          |
| suporter_companion               | Spanish: acompañantes simpatizantes     |

+ Parameters
    + venue_id (required, text) ... Identifies a specific venue.
    + capacity_id (required, text) ... Identifies a venue's capacity.
    + id (optional, text) ... Filter by a given event.
    + page (optional, number) ... Paginate response to the given page number.

### List All Venue Events [GET]

+ Request

    + Headers

            Authorization: Bearer OAUTH2_TOKEN
            Accept: application/json

+ Response 200 (application/json)

        {
          "collection":
          {
            "version": "1.0",
            "href": "http://www.oneboxtm.com/venueconfig-api/1.0/venues/51/capacities/1/events",
            "trace_id": "94abc26e-173a-4ab2-a71b-863aed20f656",
            "span_id": "34abc26e-173a-4ab2-a71b-863aed20f622",
            "request_date": "2015-08-05T08:40:51.620Z",
            "http_status_code": 200,
            "error_code": "",
            "error_description": "",
            "parameters":
            {
              "venue_id": "51",
              "capacity_id": "1",
              "page": 2
            },
            "events": [
              {
                "id": "125",
                "name": "Partido de prueba",
                "version": 1234567890,
                "update_date" : "2015-11-12T17:54:00+01:00"
                "capacity_id": "1",
                "activity_id": "2",
                "round": "10",
                "date": "2015-10-30T17:00:00+01:00",
                "final_date": true,
                "season": "14-15",
                "zone_selling": true,
                "second_market": true,
                "package_selling": false,
                "partner_selling": true,
                "fun_selling": false,
                "released_seats_selling": true,
                "early_released_seats_selling": true,
                "available": true,
                "general_admission_start_date": "2015-10-30T17:00:00+01:00",
                "general_admission_end_date": "2015-10-30T17:00:00+01:00",
                "general_admission_no_print_start_date": "2015-10-30T17:00:00+01:00",
                "general_admission_no_print_end_date": "2015-10-30T17:00:00+01:00",
                "supporter_start_date": "2015-10-30T17:00:00+01:00",
                "supporter_end_date": "2015-10-30T17:00:00+01:00",
                "supporter_no_print_start_date": "2015-10-30T17:00:00+01:00",
                "supporter_no_print_end_date": "2015-10-30T17:00:00+01:00",
                "subscriber_start_date": "2015-10-30T17:00:00+01:00",
                "subscriber_end_date": "2015-10-30T17:00:00+01:00",
                "subscriber_no_print_start_date": "2015-10-30T17:00:00+01:00",
                "subscriber_no_print_end_date": "2015-10-30T17:00:00+01:00",
                "partner_start_date": "2015-10-30T17:00:00+01:00",
                "partner_end_date": "2015-10-30T17:00:00+01:00",
                "partner_no_print_start_date": "2015-10-30T17:00:00+01:00",
                "partner_no_print_end_date": "2015-10-30T17:00:00+01:00",
                "general_admission_tickets_limit": 1,
                "preferred_tickets_limit": 1,
                "supporter_companion_tickets_limit": 2,
                "supporter_tickets_limit:" 3,
                "id_reference": 22,
                "parent_zones": [
                  {
                    "id": "1",
                    "name": "GRADA PREFERENCIAL",
                    "update_date": "2015-10-30T17:00:00+01:00",
                    "zones": [
                        {
                          "id": "126",
                          "name": "GRADA PREFERENCIA BAJA",
                          "gates": "13"
                        },
                        {
                          "id": "127",
                          "name": "GRADA PREFERENCIA ALTA",
                          "gates": "13-54"
                        }
                      ],
                      "prices": [
                        {
                          "id": "50",
                          "name": "Grada PREF BAJA",
                          "price": 60,00
                        }
                      ]
                  },
                  {
                    "id": "2",
                    "name": "GRADA VIP",
                    "update_date": "2015-10-30T17:00:00+01:00",
                    "zones": [
                        {
                          "id": "12",
                          "name": "GRADA VIP BAJA",
                          "gates": "1"
                        },
                        {
                          "id": "13",
                          "name": "GRADA VIP ALTA",
                          "gates": "23"
                        }
                      ],
                      "prices": [
                        {
                          "id": "50",
                          "name": "Grada PREF BAJA",
                          "price": 60,00
                        }
                      ]
                  }
                ]
              }
          ],

          "links": [
            {
              "name": "next_page",
              "prompt": "Next",
              "rel": "next",
              "href": "http://www.oneboxtm.com/venueconfig-api/1.0/venues/125/capacities/1/events/?page=3",
              "render": "link"
            },
            {
              "name": "previous_page",
              "prompt": "Bext",
              "rel": "back",
              "href": "http://www.oneboxtm.com/venueconfig-api/1.0/venues/125/capacities/1/events/?page=1",
              "render": "link"
            }
          ]
         }
        }

+ Response 400 (application/json)

        {
          "collection":
          {
            "version": "1.0",
            "href": "http://www.oneboxtm.com/venueconfig-api/1.0/venues/adsf/capacities/1/events",
            "trace_id": "94abc26e-173a-4ab2-a71b-863aed20f656",
            "span_id": "34abc26e-173a-4ab2-a71b-863aed20f622",
            "request_date": "2015-08-05T08:40:51.620Z",
            "http_status_code": 400,
            "error_code": "Bad Request",
            "error_description": "There was a syntax error, check your params request and try it again."
            "parameters":
            {
              "venue_id": "adsf",
              "capacity_id": "1"
            },
            "links": []
          }
        }

+ Request /venueconfig-api/1.0/venues/125/capacities/1/events

    + Headers

            Accept: application/json

+ Response 401 (application/json)

        {
          "collection":
          {
            "version": "1.0",
            "href": "http://www.oneboxtm.com/venueconfig-api/1.0/venues/125/capacities/1/events",
            "trace_id": "94abc26e-173a-4ab2-a71b-863aed20f656",
            "span_id": "34abc26e-173a-4ab2-a71b-863aed20f622",
            "request_date": "2015-08-05T08:40:51.620Z",
            "http_status_code": 401,
            "error_code": "Unauthorized",
            "error_description": "Full authentication is required to access this resource"
            "parameters":
            {
              "venue_id": "124",
              "capacity_id": "1",
              "page": 1
            },
            "venues": [],
            "links": []
          }
        }

## Venue's capacity's events Resource Operations [/venueconfig-api/1.0/venues/{venue_id}/capacities/{capacity_id}/events/{id}{?version,latest_from}]

Retrieve a concrete resource representation of a venue's capacity's event specified by its *id*. For a concrete event a specific version of the event can be retrieved using the parameter `version`. If you do not know the version you have 2 possibilities:
 * Getting the latest version by not specifying `version` nor `latest_from`.
 * Specify the last valid version that you know as `latest_from` value. This will cause to get the latest version of the venue if there is one. In case that there is no newer version a `404` is returned.

+ Parameters
    + venue_id (required, text) ... Identifies a specific venue.
    + capacity_id (required, text) ... Identifies a venue's capacity.
    + id (text) ... The event identifier
    + version (optional, number) ... Return a specific version of the event. Mutualy exclusive with `latest_from`
    + latest_from (optional, number) ... Given a version it returns the most recent event's version grather than the provided version. Mutualy exclusive with `version`

### Retieve a single venue's event resource [GET]
+ Request /venueconfig-api/1.0/venues/51/capacities/1/events/125
    + Headers

            Authorization: Bearer OAUTH2_TOKEN
            Accept: application/json

+ Response 200 (application/json)

        {
            "collection":
            {
                "version": "1.0",
                "href": "http://www.oneboxtm.com/venueconfig-api/1.0/venues/51/capacities/1/events/125",
                "trace_id": "94abc26e-173a-4ab2-a71b-863aed20f656",
                "span_id": "34abc26e-173a-4ab2-a71b-863aed20f622",
                "request_date": "2015-08-05T08:40:51.620Z",
                "http_status_code": 200,
                "error_code": "",
                "error_description": "",
                "parameters":
                {
                 "venue_id": "51",
                 "capacity_id": "1",
                 "id": "125"
                },
                "events": [
                 {
                   "id": "125",
                   "name": "Partido de prueba",
                   "version": 1234567890,
                   "update_date" : "2015-11-12T17:54:00+01:00"
                   "capacity_id": "1",
                   "activity_id": "2",
                   "round": "10",
                   "date": "2015-10-30T17:00:00+01:00",
                   "final_date": true,
                   "season": "14-15",
                   "zone_selling": true,
                   "second_market": true,
                   "package_selling": false,
                   "partner_selling": true,
                   "fun_selling": false,
                   "released_seats_selling": true,
                   "early_released_seats_selling": true,
                   "available": true,
                   "general_admission_start_date": "2015-10-30T17:00:00+01:00",
                   "general_admission_end_date": "2015-10-30T17:00:00+01:00",
                   "general_admission_no_print_start_date": "2015-10-30T17:00:00+01:00",
                   "general_admission_no_print_end_date": "2015-10-30T17:00:00+01:00",
                   "supporter_start_date": "2015-10-30T17:00:00+01:00",
                   "supporter_end_date": "2015-10-30T17:00:00+01:00",
                   "supporter_no_print_start_date": "2015-10-30T17:00:00+01:00",
                   "supporter_no_print_end_date": "2015-10-30T17:00:00+01:00",
                   "subscriber_start_date": "2015-10-30T17:00:00+01:00",
                   "subscriber_end_date": "2015-10-30T17:00:00+01:00",
                   "subscriber_no_print_start_date": "2015-10-30T17:00:00+01:00",
                   "subscriber_no_print_end_date": "2015-10-30T17:00:00+01:00",
                   "partner_start_date": "2015-10-30T17:00:00+01:00",
                   "partner_end_date": "2015-10-30T17:00:00+01:00",
                   "partner_no_print_start_date": "2015-10-30T17:00:00+01:00",
                   "partner_no_print_end_date": "2015-10-30T17:00:00+01:00",
                   "general_admission_tickets_limit": 1,
                   "preferred_tickets_limit": 1,
                   "supporter_companion_tickets_limit": 2,
                   "supporter_tickets_limit:" 3,
                   "id_reference": 22,
                   "parent_zones": [
                     {
                       "id": "1",
                       "name": "GRADA PREFERENCIAL",
                       "update_date": "2015-10-30T17:00:00+01:00",
                       "zones": [
                           {
                             "id": "126",
                             "name": "GRADA PREFERENCIA BAJA",
                             "gates": "13"
                           },
                           {
                             "id": "127",
                             "name": "GRADA PREFERENCIA ALTA",
                             "gates": "13-54"
                           }
                         ],
                         "prices": [
                           {
                             "id": "50",
                             "name": "Grada PREF BAJA",
                             "price": 60,00
                           }
                         ]
                     },
                     {
                       "id": "2",
                       "name": "GRADA VIP",
                       "update_date": "2015-10-30T17:00:00+01:00",
                       "zones": [
                           {
                             "id": "12",
                             "name": "GRADA VIP BAJA",
                             "gates": "1"
                           },
                           {
                             "id": "13",
                             "name": "GRADA VIP ALTA",
                             "gates": "23"
                           }
                         ],
                         "prices": [
                           {
                             "id": "50",
                             "name": "Grada PREF BAJA",
                             "price": 60,00
                           }
                         ]
                     }
                   ]
                 }
                ],
                "links": []
            }
        }

+ Request http://www.oneboxtm.com/venueconfig-api/1.0/venues/125/capacities/1/events/asdfa
    + Headers

            Authorization: Bearer OAUTH2_TOKEN
            Accept: application/json
+ Response 400 (application/json)

        {
            "collection":
            {
               "version": "1.0",
               "href": "http://www.oneboxtm.com/venueconfig-api/1.0/venues/125/capacities/1/events/asdfa",
               "trace_id": "94abc26e-173a-4ab2-a71b-863aed20f656",
               "span_id": "34abc26e-173a-4ab2-a71b-863aed20f622",
               "request_date": "2015-08-05T08:40:51.620Z",
               "http_status_code": 400,
               "error_code": "Bad Request",
               "error_description": "There was a syntax error, check your params request and try it again."
               "parameters":
               {
                 "venue_id": "125",
                 "event_id": "adsf",
                 "capacity_id": "1"
             },events


+ Request /venueconfig-api/1.0/venues/125/events/12
    + Headers

            Accept: application/json
+ Response 401 (application/json)

        {
            "collection":
                {
                "version": "1.0",
                "href": "http://www.oneboxtm.com/venueconfig-api/1.0/venues/125/capacities/1/events/12",
                "trace_id": "94abc26e-173a-4ab2-a71b-863aed20f656",
                "span_id": "34abc26e-173a-4ab2-a71b-863aed20f622",
                "request_date": "2015-08-05T08:40:51.620Z",
                "http_status_code": 401,
                "error_code": "Unauthorized",
                "error_description": "Full authentication is required to access this resource"
                "parameters":
                {
                 "venue_id": "125",
                 "capacity_id": "1",
                 "id": "12",
                 "page": 1
                },
                "venues": [],
                "links": []
            }
        }

## Venue seating capacity details Collection [/venueconfig-api/1.0/venues/{venue_id}/capacities{?id,page}]
List all the seating capacities from a given venue with its key data. It is also allowed to filtering by Id and paging.
The following table contains the Spanish Soccer compatibility response fields descriptions:

| Response Field                   | Description                             |
|----------------------------------|-----------------------------------------|
| entrance                         | Spanish: boca                           |
| gate                             | Spanish: puerta                         |
| block                            | Spanish: escalera                       |
| sector                           | Spanish: vomitorio                      |

+ Parameters
    + venue_id (required, text) ... Identifies a specific venue.
    + id (optional, text) ... Filter by a given seating capacity.
    + page (optional, number) ... Paginate response to the given page number.

### List All Seating Capacities of a given Venue/Event [GET]

+ Request

    + Headers

            Authorization: Bearer OAUTH2_TOKEN
            Accept: application/json

+ Response 200 (application/json)

        {
          "collection":
          {
            "version": "1.0",
            "href": "http://www.oneboxtm.com/venueconfig-api/1.0/venues/125/capacities",
            "trace_id": "94abc26e-173a-4ab2-a71b-863aed20f656",
            "span_id": "34abc26e-173a-4ab2-a71b-863aed20f622",
            "request_date": "2015-08-05T08:40:51.620Z",
            "http_status_code": 200,
            "error_code": "",
            "error_description": "",
            "parameters":
            {
              "venue_id": "125",
              "id": "1",
              "page": 2
            },
            "capacities": [
              {
                "id": "1",
                "name": "LIGA",
                "version": 1234567890,
                "creation_date": "",
                "update_date": "2014-07-30T14:39:33.48+02:00",
                "zones": [
                  {
                    "id": "1",
                    "name": "GRADA PREFERENCIAL",
                    "version": 1234567890,
                    "gates": "54",
                    "seats": [
                        {
                          "id": "126",
                          "row": 20,
                          "row_name": "20"
                          "seat": 3,
                          "seat_name": "3A",
                          "entrance": "",
                          "gate": "1",
                          "block": "1",
                          "sector": ""
                        },
                        {
                          "id": "127",
                          "row": 20,
                          "row_name": "20"
                          "seat": 3,
                          "seat_name": "3A",
                          "entrance": "",
                          "gate": "1",
                          "block": "1",
                          "sector": ""
                        }
                    ]
                  },
                  {
                    "id": "2",
                    "name": "GRADA VIP",
                    "version": 1234567890,
                    "creation_date": "",
                    "update_date": "2014-07-30T14:39:33.48+02:00",
                    "gates": "2",
                    "seats": [
                        {
                          "id": "128",
                          "row": 20,
                          "row_name": "20"
                          "seat": 3,
                          "seat_name": "3A",
                          "entrance": "A",
                          "gate": "1",
                          "block": "1",
                          "sector": ""
                        },
                        {
                          "id": "129",
                          "row": 20,
                          "row_name": "20"
                          "seat": 3,
                          "seat_name": "3A",
                          "entrance": "A",
                          "gate": "1",
                          "block": "1",
                          "sector": ""
                        }
                    ]
                  }
                ]
              }
          ],
          "links": [
            {
              "name": "next_page",
              "prompt": "Next",
              "rel": "next",
              "href": "http://www.oneboxtm.com/venueconfig-api/1.0/venues/125/capacities?page=3",
              "render": "link"
            },
            {
              "name": "previous_page",
              "prompt": "Bext",
              "rel": "back",
              "href": "http://www.oneboxtm.com/venueconfig-api/1.0/venues/125/capacities?page=1",
              "render": "link"
            }
          ]
         }
        }

+ Request /venueconfig-api/1.0/venues/asdf/capacities

    + Headers

            Authorization: Bearer OAUTH2_TOKEN
            Accept: application/json

+ Response 400 (application/json)

        {
          "collection":
          {
            "version": "1.0",
            "href": "http://www.oneboxtm.com/venueconfig-api/1.0/venues/asdf/capacities",
            "trace_id": "94abc26e-173a-4ab2-a71b-863aed20f656",
            "span_id": "34abc26e-173a-4ab2-a71b-863aed20f622",
            "request_date": "2015-08-05T08:40:51.620Z",
            "http_status_code": 400,
            "error_code": "Bad Request",
            "error_description": "There was a syntax error, check your params request and try it again."
            "parameters":
            {
              "venue_id": "asdf"
            },
            "links": []
          }
        }
+ Request /venueconfig-api/1.0/venues/125/capacities
    + Headers

            Accept: application/json

+ Response 401 (application/json)

        {
          "collection":
          {
            "version": "1.0",
            "href": "http://www.oneboxtm.com/venueconfig-api/1.0/venues/125/capacities",
            "trace_id": "94abc26e-173a-4ab2-a71b-863aed20f656",
            "span_id": "34abc26e-173a-4ab2-a71b-863aed20f622",
            "request_date": "2015-08-05T08:40:51.620Z",
            "http_status_code": 401,
            "error_code": "Unauthorized",
            "error_description": "Full authentication is required to access this resource"
            "parameters":
            {
              "venue_id": "125"
            },
            "links": []
          }
        }



## Venue seating capacity Resource Operations [/venueconfig-api/1.0/venues/{venue_id}/capacities/{id}{?version,latest_from}]

Retrieve a concrete resource representation of a venue's seating capacity specified by its *id*. For a concrete Venue seating capacity a specific version of the event can be retrieved using the parameter `version`. If you do not know the version you have 2 possibilities:
 * Getting the latest version by not specifying `version` nor `latest_from`.
 * Specify the last valid version that you know as `latest_from` value. This will cause to get the latest version of the venue's seating capacity if there is one. In case that there is no newer version a `404` is returned.

+ Parameters
    + venue_id (required, text) ... Identifies a specific venue.
    + id (optional, text) ... Filter by a given seating capacity.
    + version (optional, number) ... Return a specific version of the event. Mutualy exclusive with `latest_from`
    + latest_from (optional, number) ... Given a version it returns the most recent event's version grather than the provided version. Mutualy exclusive with `version`

### Retieve a single venue's Venue seating capacity resource [GET]

+ Request

    + Headers

            Authorization: Bearer OAUTH2_TOKEN
            Accept: application/json

+ Response 200 (application/json)

        {
          "collection":
          {
            "version": "1.0",
            "href": "http://www.oneboxtm.com/venueconfig-api/1.0/venues/125/capacities/1",
            "trace_id": "94abc26e-173a-4ab2-a71b-863aed20f656",
            "span_id": "34abc26e-173a-4ab2-a71b-863aed20f622",
            "request_date": "2015-08-05T08:40:51.620Z",
            "http_status_code": 200,
            "error_code": "",
            "error_description": "",
            "parameters":
            {
              "venue_id": "125",
              "id": "1",
            },
            "capacities": [
              {
                "id": "1",
                "name": "LIGA",
                "version": 1234567890,
                "creation_date": "",
                "update_date": "2014-07-30T14:39:33.48+02:00",
                "zones": [
                  {
                    "id": "1",
                    "name": "GRADA PREFERENCIAL",
                    "gates": "54",
                    "seats": [
                        {
                          "id": "126",
                          "row": 20,
                          "row_name": "20"
                          "seat": 3,
                          "seat_name": "3A",
                          "entrance": "",
                          "gate": "1",
                          "block": "1",
                          "sector": ""
                        },
                        {
                          "id": "127",
                          "row": 20,
                          "row_name": "20"
                          "seat": 3,
                          "seat_name": "3A",
                          "entrance": "",
                          "gate": "1",
                          "block": "1",
                          "sector": ""
                        }
                    ]
                  },
                  {
                    "id": "2",
                    "name": "GRADA VIP",
                    "creation_date": "",
                    "update_date": "2014-07-30T14:39:33.48+02:00",
                    "gates": "2",
                    "seats": [
                        {
                          "id": "128",
                          "row": 20,
                          "row_name": "20"
                          "seat": 3,
                          "seat_name": "3A",
                          "entrance": "A",
                          "gate": "1",
                          "block": "1",
                          "sector": ""
                        },
                        {
                          "id": "129",
                          "row": 20,
                          "row_name": "20"
                          "seat": 3,
                          "seat_name": "3A",
                          "entrance": "A",
                          "gate": "1",
                          "block": "1",
                          "sector": ""
                        }
                    ]
                  }
                ]
              }
          ],
          "links": []
         }
        }

+ Request /venueconfig-api/1.0/venues/asdf/capacities
    + Headers

            Accept: application/json
            Authorization: Bearer OAUTH2_TOKEN

+ Response 400 (application/json)

        {
          "collection":
          {
            "version": "1.0",
            "href": "http://www.oneboxtm.com/venueconfig-api/1.0/venues/asdf/capacities",
            "trace_id": "94abc26e-173a-4ab2-a71b-863aed20f656",
            "span_id": "34abc26e-173a-4ab2-a71b-863aed20f622",
            "request_date": "2015-08-05T08:40:51.620Z",
            "http_status_code": 400,
            "error_code": "Bad Request",
            "error_description": "There was a syntax error, check your params request and try it again."
            "parameters":
            {
              "venue_id": "asdf"
            },
            "links": []
          }
        }
+ Request /venueconfig-api/1.0/venues/125/capacities/1
    + Headers

            Accept: application/json

+ Response 401 (application/json)

        {
          "collection":
          {
            "version": "1.0",
            "href": "http://www.oneboxtm.com/venueconfig-api/1.0/venues/125/capacities",
            "trace_id": "94abc26e-173a-4ab2-a71b-863aed20f656",
            "span_id": "34abc26e-173a-4ab2-a71b-863aed20f622",
            "request_date": "2015-08-05T08:40:51.620Z",
            "http_status_code": 401,
            "error_code": "Unauthorized",
            "error_description": "Full authentication is required to access this resource"
            "parameters":
            {
              "venue_id": "125",
              "id": "1"
            },
            "links": []
          }
        }
