FORMAT: 1A
HOST: http://onebox-venueconfig-api.getsandbox.com/

# onebox-venueconfig-api

 API to get all the venue configurations from any external ticketing system.

 To do so, we have used a **API Blueprint** standard, **apiary** as an online editing and mocking tool, **aglio** to document it, **getsandbox** as a sandbox provider, **atom** as local editor and **mockapi** as a local sandbox.
 + [API Blueprint](https://apiblueprint.org/)
 + [apiary.io](http://docs.oneboxvenueconfigapi.apiary.io/)
 + [getsandbox.com](http://onebox-venueconfig-api.getsandbox.com/)
 + [aglio](https://github.com/danielgtaylor/aglio)
 + [atom](http://atom.io)
 + [mockapi](https://github.com/joliva-ob/mockapi)
 + [github](https://github.com/joliva-ob/onebox-venueconfig-api)

## Venues Collection [/venueconfig-api/v1.0/venues{?id,page}]
List all the venues with its key data and the activities allowed for  each one. It is also allowed filtering by Id and paging.

### List All Events [GET]

+ Request

  + Headers

            Authorization: Bearer OAUTH2_TOKEN
            Accept: application/json

+ Parameters
    + id (optional, text) ... Filter by a given venue id.
    + page (optional, number) ... Paginate response to the given page number.

+ Response 200 (application/json)

        {
          "collection":
          {
            "version": "1.0",
            "href": "http://www.oneboxtm.com/venueconfig-api/v1.0/venues",
            "trace_id": "94abc26e-173a-4ab2-a71b-863aed20f656",
            "request_date": "2015-08-05T08:40:51.620Z",
            "parameters":
            {
              "id": "",
              "page": 2
            },
            "venues": [
              {
                "id": "51",
                "name": "Futbol Club Barcelona",
                "ip": "10.234.22.5",
                "port": 60000,
                "capacities": [
                  {
                    "id": "1",
                    "name": "LIGA",
                    "activities": [
                      {
                        "id": "1",
                        "name": "LIGA"
                      },
                      {
                        "id": "2",
                        "name": "SUPERCOPA"
                      },
                      {
                        "id": "3",
                        "name": "CHAMPIONS"
                      },
                      {
                        "id": "4",
                        "name": "COPA DEL REY"
                      }
                    ]
                  },
                  {
                    "id": "2",
                    "name": "PARKING",
                    "activities": [
                      {
                        "id": "1",
                        "name": "PARKING"
                      }
                    ]
                  },
                  {
                    "id": "3",
                    "name": "EUROPA",
                    "activities": [
                      {
                        "id": "1",
                        "name": "UEFA"
                      },
                      {
                        "id": "2",
                        "name": "CHAMPIONS"
                      }
                    ]
                  },
                  {
                    "id": "4",
                    "name": "CONCIERTOS",
                    "activities": [
                      {
                        "id": "1",
                        "name": "UNICA"
                      }
                    ]
                  }
                ],
                "settings":
                {
                  "confirmation_release_time": 5,
                  "cancellation_release_time": 60,
                  "pre_order_trials_limit": 3,
                  "second_market": false,
                  "partners_selling": true,
                  "max_tickets_order": 5,
                  "allowed_seat_status": [
                    {
                      "id": "L"
                    },
                    {
                      "id": "S"
                    },
                    {
                      "id": "X"
                    }
                  ],
                  "pending_booking_seat_status": "Z",
                  "pending_booking_confirmation_allowed": false
                }
              },
              {
                "id": "37",
                "name": "Club Atlético de Madrid",
                "ip": "10.234.22.1",
                "port": 60000,
                "capacities": [
                  {
                    "id": "1",
                    "name": "LIGA",
                    "activities": [
                      {
                        "id": "1",
                        "name": "LIGA"
                      },
                      {
                        "id": "2",
                        "name": "SUPERCOPA"
                      },
                      {
                        "id": "3",
                        "name": "CHAMPIONS"
                      },
                      {
                        "id": "4",
                        "name": "COPA DEL REY"
                      }
                    ]
                  },
                  {
                    "id": "2",
                    "name": "PARKING",
                    "activities": [
                      {
                        "id": "1",
                        "name": "PARKING"
                      }
                    ]
                  },
                  {
                    "id": "3",
                    "name": "EUROPA",
                    "activities": [
                      {
                        "id": "1",
                        "name": "UEFA"
                      },
                      {
                        "id": "2",
                        "name": "CHAMPIONS"
                      }
                    ]
                  },
                  {
                    "id": "4",
                    "name": "CONCIERTOS",
                    "activities": [
                      {
                        "id": "1",
                        "name": "UNICA"
                      }
                    ]
                  }
                ],
                "settings":
                {
                  "confirmation_release_time": 5,
                  "cancellation_release_time": 60,
                  "pre_order_trials_limit": 3,
                  "second_market": false,
                  "partners_selling": true,
                  "max_tickets_order": 5,
                  "allowed_seat_status": [
                    {
                      "id": "L"
                    },
                    {
                      "id": "S"
                    },
                    {
                      "id": "X"
                    }
                  ],
                  "pending_booking_seat_status": "Z",
                  "pending_booking_confirmation_allowed": false
                }
              }
            ],
            "links": [
              {
                "name": "next_page",
                "prompt": "Next",
                "rel": "next",
                "href": "venues/page/3",
                "render": "link"
              },
              {
                "name": "previous_page",
                "prompt": "Bext",
                "rel": "back",
                "href": "venues/page/1",
                "render": "link"
              }
            ]

          }
        }

+ Response 201 (application/json)

+ Response 400 (application/json)

        {
          "error": "Bad request",
          "error_description": "There was a syntax error, check your params request and try it again."
        }

+ Response 401 (application/json)

        {
          "error": "unauthorized",
          "error_description": "Full authentication is required to access this resource"
        }
